version: '3'
services:
  php:
    container_name: test-auth-php
    build:
      context: ./docker/php
    volumes:
      - './:/var/www/html/'

  nginx:
    container_name: test-auth-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html/'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    container_name: test-auth-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'